{% set name = "hnswlib" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e275686e31067f921d72d2e411ff541b8abcbea0dcf0c5dc5eeb7da2b67c171

build:
  number: 0
  skip: true  # [win or py27]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=42
    - pybind11 >=2.0
    - numpy >=1.10.0
  run:
    - python
    - numpy

test:
  imports:
    - hnswlib

about:
  home: https://github.com/nmslib/hnswlib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python bindings for Hnswlib, a fast approximate nearest neighbor search package.
  dev_url: https://github.com/nmslib/hnswlib

extra:
  recipe-maintainers:
    - yihming
    - bli25broad
    - yurymalkov
